# Generated by Django 4.1.7 on 2023-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_page', '0002_allteams_team_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allteams',
            old_name='team_color',
            new_name='team_color_one',
        ),
        migrations.AddField(
            model_name='allteams',
            name='team_color_two',
            field=models.CharField(default='', max_length=7),
        ),
    ]
