# Generated by Django 4.1.7 on 2023-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_page', '0003_rename_team_color_allteams_team_color_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allteams',
            name='team_logo',
            field=models.URLField(default=''),
        ),
    ]
